name: Mobile production update

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: true

jobs:
  approve:
    name: Approve production update
    type: require-approval

  publish:
    name: Publish to production
    needs: [approve]
    type: update
    environment: production
    params:
      platform: ios
      channel: production
      message: ${{ inputs.message }}
      private_key_path: $UPDATES_SIGNING_KEY
      upload_sentry_sourcemaps: true
