// Generated by `superset plugins publish`. Do not edit.
//
// The first-party marketplace's published manifests, bundled so the API can
// resolve a plugin without fetching anything. This is deliberately not
// client-supplied: a manifest drives token_url and the proxy target, so
// trusting one from a request would be an exfiltration path.

export const FIRST_PARTY_MANIFESTS = {
	"github": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "github",
		"version": "1.0.1",
		"description": "Work with issues, pull requests, and CI across your repositories.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"github",
			"issues",
			"pull-requests",
			"ci",
			"code-review"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "GitHub",
					"category": "Developer tools",
					"icon": "github"
				},
				"connector": {
					"slug": "github"
				},
				"mcp": {
					"type": "streamable-http",
					"url": "https://api.githubcopilot.com/mcp/"
				}
			}
		},
		"skills": [
			{
				"name": "ci-triage",
				"description": "Diagnose a failing GitHub Actions run — find the first real error in the logs, tell a flake apart from a genuine failure, and identify the commit that broke it. Use when checks are red on a PR, a workflow failed, the build is broken, CI is flaky, or the user asks why a run failed or whether a failure is real."
			},
			{
				"name": "issue-triage",
				"description": "Triage a GitHub issue into something actionable — reproduce the claim, find duplicates, judge severity, and apply labels, milestone, and assignee. Use when the user asks to triage an issue, sort the backlog, deal with new issues, check whether a bug is already reported, or says \"what should we do with this issue\"."
			}
		]
	} as const,
	"linear": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "linear",
		"version": "1.5.2",
		"description": "Plan and build products: create, search, and update Linear issues.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"linear",
			"issues",
			"project-management",
			"planning"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "Linear",
					"category": "Productivity",
					"icon": "linear"
				},
				"connector": {
					"slug": "linear"
				},
				"mcp": {
					"type": "streamable-http",
					"url": "https://mcp.linear.app/mcp"
				}
			}
		},
		"skills": [
			{
				"name": "duplicate-sweep",
				"description": "Find and merge duplicate Linear issues — group reports of the same underlying bug, pick the survivor, and move the evidence across. Use when the backlog has grown noisy, someone asks whether an issue is already reported, or you are cleaning up before planning."
			},
			{
				"name": "file-issue",
				"description": "Turn a rough report into a Linear issue someone can pick up — reproduce the claim, check for duplicates, and fill in team, priority, and labels. Use when the user says to file, open, or create an issue, hands over a bug report or error, or asks to get something into Linear."
			},
			{
				"name": "project-status",
				"description": "Draft a Linear project status update from what actually moved — progress, risks, and the one decision that needs making. Use when someone asks for a project update, a status post, where a project stands, whether it will land on time, or what to tell stakeholders."
			}
		]
	} as const,
	"notion": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "notion",
		"version": "1.0.3",
		"description": "Search, read, and write your Notion workspace: pages, databases, and comments.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"notion",
			"docs",
			"notes",
			"knowledge-base",
			"wiki"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "Notion",
					"category": "Productivity",
					"icon": "notion"
				},
				"connector": {
					"slug": "notion_mcp"
				},
				"mcp": {
					"type": "streamable-http",
					"url": "https://mcp.notion.com/mcp"
				}
			}
		},
		"skills": [
			{
				"name": "find-in-notion",
				"description": "Find what the workspace already says before you answer or write — search Notion, tell the canonical page from the stale copy, and cite what you used. Use when the user asks what's in Notion, refers to a doc, spec, or meeting note, or asks a question the workspace probably already answers."
			},
			{
				"name": "write-to-notion",
				"description": "Write a page into Notion that someone else can find and trust — pick the right parent, check for the page that already exists, and structure it for a reader who was not in this conversation. Use when the user says to write up, document, save, or capture something in Notion, or to update an existing page."
			}
		]
	} as const,
	"slack": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "slack",
		"version": "1.2.3",
		"description": "Search, read, and post across your Slack workspace: channels, DMs, and threads.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"slack",
			"chat",
			"messages",
			"communication",
			"search"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "Slack",
					"category": "Communication",
					"icon": "slack"
				},
				"connector": {
					"slug": "slack"
				}
			}
		},
		"skills": []
	} as const,
	"gmail": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "gmail",
		"version": "1.1.5",
		"description": "Read, search, send, and organize mail in your Gmail account.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"gmail",
			"email",
			"mail",
			"google",
			"inbox"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "Gmail",
					"category": "Communication",
					"icon": "gmail"
				},
				"connector": {
					"slug": "google"
				}
			}
		},
		"skills": []
	} as const,
} as const;

export type FirstPartyPluginName = keyof typeof FIRST_PARTY_MANIFESTS;

export function firstPartyManifest(
	name: string,
): (typeof FIRST_PARTY_MANIFESTS)[FirstPartyPluginName] | null {
	if (!Object.hasOwn(FIRST_PARTY_MANIFESTS, name)) return null;
	return (FIRST_PARTY_MANIFESTS as Record<string, unknown>)[
		name
	] as (typeof FIRST_PARTY_MANIFESTS)[FirstPartyPluginName];
}
