import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const declarations = readFileSync(
	join(root, "node_modules/react-icons/pi/index.d.ts"),
	"utf8",
);
const names = [
	...new Set(
		[
			...declarations.matchAll(/export declare const (Pi[A-Za-z0-9]+Fill)\b/g),
		].map((match) => match[1] as string),
	),
].sort();

const keyOf = (name: string) =>
	name
		.slice(2, -4)
		.replace(/(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])/g, "-")
		.toLowerCase();

const output = [
	"// Generated by scripts/generate-project-icons.ts from react-icons/pi (Phosphor, fill weight).",
	'import type { IconType } from "react-icons";',
	"import {",
	...names.map((name) => `\t${name},`),
	'} from "react-icons/pi";',
	"",
	"export const PROJECT_ICONS: Record<string, IconType> = {",
	...names.map((name) => `\t"${keyOf(name)}": ${name},`),
	"};",
	"",
].join("\n");

writeFileSync(
	join(
		root,
		"src/renderer/routes/_authenticated/_dashboard/hooks/useProjectIcons/icons.ts",
	),
	output,
);
console.log(`Generated ${names.length} project icons`);
